gamma: 0.99
epsilon: 1.0
epsilon_decay: 0.999
learning_rate: 0.001
batch_size: 32
train_start: 250
mem_size: 50000
total_episodes: 1000
in_channels: 1
input_size_enc: 6048
hidden_size_enc: 6048
input_size_dec: 6048
hidden_size_dec: 6048
input_size_fc: 1536
nr_layers_enc: 3
nr_layers_dec: 1
attention_mechanism: 'soft'
environment: 'Breakout-v0'