gamma: 0.99
epsilon: 1
epsilon_decay: 0.999
epsilon_min: 0.05
learning_rate: 0.001
batch_size: 32
train_start: 250
k_target: 1000
mem_size: 50000
total_episodes: 1000
input_length: 4
in_channels: 1
input_size_enc: 512
hidden_size_enc: 512
input_size_dec: 512
hidden_size_dec: 512
input_size_fc: 6144
nr_layers_enc: 4
nr_layers_dec: 4
alignment_function: 'dot'
attention_mechanism: 'soft'
vector_combination: 'concat'
environment: 'Breakout-v0'