gamma: 0.99
epsilon: 1
epsilon_decay: 0.999
epsilon_min: 0.05
learning_rate: 0.001
batch_size: 32
train_start: 250
k_target: 1000
mem_size: 50000
total_episodes: 300
input_length: 4
in_channels: 1
max_filters: 128
nr_layers_enc: 4
nr_layers_dec: 4
environment: 'Breakout-v0'